### ISSUE TITLE
Ability to specify priority in autoSetDimension:toSize:relation:

### ISSUE THREAD

**Issue by ammojamo** [smileyborg/PureLayout#41]
This is more just a question. Why does the `-[UIView autoSetDimension:toSize:relation:]` method not have a variant that allows us to specify the priority of the constraint?

Use case - I've just come across a scenario where I have a complex subview and I need to compress the height of that subview as much as possible. The only approach I've found that works is installing a low priority constraint that sets the subview's height to zero. Not sure if this is good practice, but I've tried several other approaches without success, e.g. content hugging priority.

It would be nice if I could achieve this using the PureLayout API - I ended up resorting to the native NSLayoutConstraint API to achieve my goal.

P.S. thanks for the awesome library, I use it constantly

**Comment by smileyborg** [comment]
Glad to hear PureLayout works for you!

As far as your situation, what you're describing actually sounds quite normal and reasonable to me. Using a low priority constraint to "exert pressure" (but be broken if necessary) is completely valid.

To your question about setting the priority, PureLayout provides a single API that can be used to set any priority on all constraints generated by PureLayout: [`+[UIView autoSetPriority:forConstraints:]`](https://github.com/smileyborg/PureLayout/blob/master/Source/ALView%2BPureLayout.h#L61) You can see an example of usage in [Demo 6](https://github.com/smileyborg/PureLayout/blob/master/Example/Example-iOS/Demos/ALiOSDemo6ViewController.m#L48). Basically, the priority you choose will apply to any and all PureLayout-created constraints in the scope of the block. (Pro tip: you can even nest blocks if needed and it will work correctly!)

There is one other option, which is to create constraints using [`+[UIView autoCreateConstraintsWithoutInstalling:]`](https://github.com/smileyborg/PureLayout/blob/master/Source/ALView%2BPureLayout.h#L54). When you use that API, all the constraints that end up being created inside the block are returned to you by that call. Then, you are free to adjust the priority of those constraints (constraint priority must be set before activating/installing constraints), and simply call `[constraints autoInstallConstraints]` afterwards. (Another pro tip: installing all your constraints at once like this can actually be more efficient in some cases than activating each constraint as it is created one by one!)

The reason that there isn't a `priority:` parameter on all the regular APIs is because that would cause a huge bloat in number of methods, since every constraint has a priority. I've found the block-based scope approach to work quite well, especially if you have a number of constraints to adjust the priority of (or you call a PureLayout API that indirectly creates many constraints).

Let me know if that all makes sense and if you have any other questions!

**Comment by ammojamo** [comment]
Thanks so much for your detailed response. That all makes complete sense. I didn't know about those block based methods - very neat! Just tested this approach and it's working perfectly. Good to know I was on the right track with my use of a low priority constraint. Cheers!

**Comment by smileyborg** [comment]
👍 Definitely take some time to look through all of the demos & associated code. When I re-wrote that example project a couple months ago, I really tried to make sure it showcased most of the features of the library. You'll probably be able to pick up some more new things there!

One other super advanced tip, you can also nest the priority blocks inside a create-without-installing block, if you like...and if you nest the create-without-installing blocks inside each other, the return value will only be for the constraints that are directly inside the scope of that block. So you can structure your layout code in fairly interesting ways and capture references to constraints quite easily without having to keep adding to a mutable array or something.

**Comment by smileyborg** [comment]
P.S. [Demo 8](https://github.com/smileyborg/PureLayout/blob/master/Example/Example-iOS/Demos/ALiOSDemo8ViewController.m) illustrates my most favorite and least used feature of the library. Extremely powerful for debugging, and writing self-documenting layout code.

**Comment by ammojamo** [comment]
That is so cool! At the moment my biggest frustration with AutoLayout in general is when I have a view with subviews that dynamically appear and disappear, especially when there is padding involved so you can't just zero out the dimensions of hidden views, instead you have to manipulate or create/destroy constraints on the fly. The code gets messy fast.
Looks like these features could be very handy for structuring layout code in complex situations so it's easier to debug and reason about.

**Comment by smileyborg** [comment]
Yeah I know what you mean. Generally, I recommend focusing on (de)composition to abstract different independent layers/components/subviews that make up your layout. Container views can help a lot with this.

I'm also a big fan of writing idempotent layout code when your different states/layouts are significantly different. Every time updateConstraints is called, you should check if the existing state (and its associated installed constraints) matches your new state. If not, remove all the currently installed constraints and install the new ones for the new state. Obviously avoid doing something if not necessary.
