### ISSUE TITLE
Constraints not autoinstalled

### ISSUE THREAD

**Issue by nmock** [smileyborg/PureLayout#42]
I have a relatively simple set of constraints I am trying to fulfill (trying to keep a table view pinned to the visible regions of the screen, however, when trying to install the constraints, it does not seem to be installing any. I am creating the table view in pure code. Any ideas as to what the issue is?
    
    // in init 
    self.tableView = [[UITableView alloc] initForAutoLayout];
    self.tableView.delegate = self;
    self.tableView.dataSource = self;
    [self.view addSubview:self.tableView];

    - (void)updateViewConstraints {
        if (!self.didSetupConstraints) {
           [self.tableView autoPinEdgesToSuperviewEdgesWithInsets:UIEdgeInsetsMake(0, 0, 0, 0) excludingEdge:ALEdgeTop];
           NSLayoutConstraint *topLayoutConstraint = [self.tableView autoPinEdge:ALEdgeTop toEdge:ALEdgeBottom ofView:self.navigationController.navigationBar withOffset:0.0];
                
            NSLog(@"%@ constraints after auto installation: %@", self.tableView, self.tableView.constraints);
		
            self.didSetupConstraints = YES;
        }
    
        [super updateViewConstraints];
    }

Output:

    <UITableView: 0x157862400; frame = (0 0; 0 0); clipsToBounds = YES; gestureRecognizers = <NSArray: 0x174252ab0>; layer = <CALayer: 0x174233180>; contentOffset: {0, 0}; contentSize: {0, 100}> constraints on setup: (
    )

**Comment by nmock** [comment]
Note: they *seem* to be working, however, I am trying to do some debugging but they aren't showing up in the constraints for the view. Am I over looking something or looking at the wrong property?

**Comment by smileyborg** [comment]
If you are doing `po tableView` or `po tableView.constraints` in the debugger, note that this does *not* print out the constraints that affect `tableView` -- this prints out constraints that have been **added** to `tableView`.

If you aren't sure what that means, before iOS 8, you had to manually add constraints to a common superview of the views being constrained. This has always been handled automatically for you by PureLayout (and was one of the very nice features it provided). As of iOS 8, there is now an `active` property on NSLayoutConstraint that does this for you behind the scenes. But of course, you may not know exactly which view the constraint was added to (it can be on any view as long as that view is a parent of **both** views being constrained).

Anyways, for **debugging purposes only**, there is a solution! Apple has an API to help (declared in a category on UIView in UIView.h): `-[UIView constraintsAffectingLayoutForAxis:]` This will return the list of constraints you are expecting, when you call it on a view. And since the horizontal and vertical axes are independent, you pass which you'd like to inspect and will only see one set at a time.

Hope that helps!

**Comment by nmock** [comment]
@smileyborg, thanks for the tips! AutoLayout has always been one of those libraries I've been meaning to get my head around and your library definitely makes it a delight. I owe you a beer, cheers!
