### ISSUE TITLE
Inconsistent Constraints (with and without animations)

### ISSUE THREAD

**Issue by bhowell2** [smileyborg/PureLayout#48]
I believe that I have found a bug of sorts, but this could be due to some lack of understanding that I possess.. I've created an example project that displays the issue.

Here is the project: https://github.com/bhowell2/PureLayoutExample

Hierarchy:
MainControllerView (full screen)
   -ChildControllerView (full screen) (just covers main view)
      -SearchFieldView (top 6% (height) of screen and 100% width)
         -SearchField (takes up 80% of width of superview and 100% height and is offset from the left by 20)
            -ActivityIndicator
      -TagScrollView (bottom 94% (height) of screen and 100% width) (scrollview)

You can see the issue when you click load view in the navigation bar. The first time, the view loads as expected.  The second time you click load view, two things happen.  The top view controller (that should take up 6% height and 100% width) shifts to the left (revealing the brown view beneath).  I really have no idea why this is. NOT ONLY does this happen, but the view resizes itself to like 1/4th of the screen...

You will notice that this does not happen when using Apple's (verbose) layout constraints.. (though there is an issue where the brown view appears too quickly.. ignore that for now!)

You may test this by setting <em>usePureLayout</em> in <em>MainViewController</em>.

You can use the animation by setting <em>useAnimations</em> in <em>MainViewController</em> as well.

I first noticed the top view shifting to the left when implementing this without an animation. When i introduced the animation it got really crazy where the view appeared at about 1/4 screen size... (And i just noticed that now it's going to 1/4 screen size with or without the animation)

Any ideas what is going on here? Am I simply setting something wrong?

(I actually made this little project to try to reproduce the top view shifting to the left that i noticed in my own project, but could not get it to reproduce here.. it showed back up when i introduced the animations -and you can see it, by the brown view beneath showing, when it's at 1/4 size, now regardless of animations)

**Comment by smileyborg** [comment]
Hi Blake!

I downloaded your sample project and ran it. I do see the differences in behavior when switching the `userPureLayout` flag as you mention. However, there is quite a bit of stuff going on in the project and it's hard for me to know where to start looking to help identify what is causing this.

Can you try to:
a) simplify and reduce the sample project to the minimum required to illustrate the issue? For example, removing views, constraints, and code that is not necessary to demonstrate the behavior.
*and/or*
b) do some investigation yourself to figure out what things are related to (and might be causing) the problem -- for example, specific constraints, or the way in which the views are added, or the view controller containment, etc -- and report back with your findings?

If you can try to isolate things a bit further, I'd be happy to help debug what is going on.

If I had to guess, I would say that this issue might be due to the PureLayout-created constraints being different than the Apple NSLayoutConstraint-created constraints. Given that PureLayout doesn't do much besides calling the same Apple NSLayoutConstraint API that you are doing directly, I doubt that this difference in behavior is actually due to something with PureLayout -- but that's just my best guess, you never know!

Thanks!

**Comment by bhowell2** [comment]
Will get back on this in the morning. As far as the "topView" (searchFieldView) shifting left - i noticed it happening when having the ActivityIndicator was added to search field.  I'll break this project down a bit more to make it more simple. (Should be able to reproduce with just UIViews)

**Comment by bhowell2** [comment]
Hey Tyler,

Thanks for taking your time to get back to me. 

I have created another, more simple, project that displays some similar, odd, behavior.  The bug seems to show up itself when either pushing/popping the navigation controller stack or adding/removing a child view controller.

I've looked at PureLayout's source code and, at least superficially, I cannot see where any of this would go wrong as it's mainly just a wrapper for NSLayoutConstraints..

I've described how this project works and the issue it in the ReadMe.md in the project: https://github.com/bhowell2/PureLayoutInconsistencyDemo

Let me know how I can help (obviously finding the issue would be the best way. I've got some other work to do for a bit, but will try to actually start debugging it in a few hours)

PureLayout is a great library you've done a great job with it - thanks!

**Comment by bhowell2** [comment]
The example i just uploaded was impractical (I don't think ui constraints are meant to change between views..? - and this is not something i'd really expect to happen in the wild..) I'm working to see If I can reproduce the issue with a more practical example right now.

**Comment by bhowell2** [comment]
I've reproduced the issue and reuploaded a MUCH more practical example: https://github.com/bhowell2/PureLayoutInconsistencyDemo

The details are in the Readme.

**Comment by bhowell2** [comment]
Just submitted an updated example (same link as above - https://github.com/bhowell2/PureLayoutInconsistencyDemo )  

There are two examples of unexpected behavior (change one variable in AppDelegate to view them).
 
They should be pretty clear in the readme.

**Comment by smileyborg** [comment]
Sorry for the delay in getting back to you, I've been quite busy the last couple days getting things together for a presentation last night. I'll be able to take a look soon and will let you know!

**Comment by bhowell2** [comment]
No worries, quite understandable! I may be doing something wrong somewhere.. But, I'm just not sure why it's behaving this way. I went through some of the source and can't see where it would go wrong.. Hopefully you'll have a little more insight when you check it out and may find the issue (it's probably me..)!

**Comment by smileyborg** [comment]
Hey Blake,

I finally got a chance to look at your updated project, sorry again for the delay -- things have been super busy here!

Anyways, regarding the first bug you mention:

> To see the bugs, uncomment lines 81 and 82. When these lines are uncommented, the white view covers the green on the left (though it is embedded as a subview of topViewSubView and therefore should be WITHIN the gray rectangle). Uncommenting line 88 will fix the issue.. Though it was causing me an issue before (the issue listed below). I reproduced the issue that I originally had with uncommenting line 88 by adding in two view controllers.

The short explanation is that this is not a bug. You are assuming that the `topSubViewSubView` (I prefer to refer to it as the white view :wink:) will be positioned "inside" of its superview (the grey view). However, this is not how things work. Here's why:

1. Generally speaking, a subview of a view is allowed to layout and render outside of the superview anytime, as long as `superview.clipsToBounds == NO`. This is regardless of whether auto layout or manual (frame-based) layout is being used. So, if the x & y position in combination with the size of the view mean that it would render "outside" of the superview it will. Of course, that's the case here.
2. In this case, the reason why the white view is rendering outside of its superview is because **its layout is ambiguous**. In other words, it is *under-constrained* -- you have added 2 constraints that correctly specify the width & height of the white view (Line 81 & 82). However, you have not added any constraints that specify the **x or y position** of the white view. This means that the auto layout engine will randomly pick any "valid" x and y position to use for your white view (where "valid" means doesn't conflict with any of the constraints you do have).

    You can test this out by adding the following code, which uses a debug API in UIView.h:
    ```
    override func viewDidAppear(animated: Bool) {
        println(topSubViewSubView.hasAmbiguousLayout()) // prints "true"
    }
    ```

   You can also call the following to request the auto layout engine pick another random valid solution, which can help visualize other possibilities and better understand what is ambiguous:
    ```
    topSubViewSubView.exerciseAmbiguityInLayout()
    ```
    Based on this, uncommenting Line 88 only fixes **part** of the issue: the x position is now fully specified, however **the y position is still ambiguous**! (The reason it looks the way you want it to is basically pure luck.) You would need to also pin the top or bottom edge of the white view, or align its horizontal axis to the axis of its superview to fix the issue completely.

Let me know if that makes sense. I'm assuming that the other bugs/issues you're seeing are due to similar problems. Don't be afraid to set a breakpoint once your layout is all set up, and use the `hasAmbiguousLayout()` and `exerciseAmbiguityInLayout()` APIs from the debugger in order to check this!

**Comment by bhowell2** [comment]
Hey Tyler,

Firstly, thank you for taking your time to even look at this and even more so for the detailed explanation! I figured I had to be doing something wrong (especially after looking at PureLayout's source), but I had no idea what it was (didn't even know about `hasAmbiguousLayout()`) going on. (Since I wasn't getting any console warnings I figured the layout constraints were good, but obviously not!)

Again, thank you for looking into it and the wonderful API.
