### ISSUE TITLE
Example of working Swift code?

### ISSUE THREAD

**Issue by davehirsch** [smileyborg/PureLayout#50]
I read in the docs about a bridging header, but I don't see one in the files, and I am having a hard time incorporating PureLayout into my Swift project.  What am I missing?  A very small working proof-of-concept project would be welcome.
This looks like a great package; I'm eager to use it.  
Thanks!

**Comment by smileyborg** [comment]
Hi Dave!

Thanks for asking about this. I definitely want to put together a sample project that shows PureLayout being used from Swift. Right now, there isn't an official one, mainly because I haven't had the time to work on it :)

In the meantime, here are 2 small projects that are using PureLayout in Swift and can at least be a starting point for you to look at:
https://github.com/smileyborg/TableViewCellWithAutoLayoutiOS8
https://github.com/smileyborg/AdaptiveAutoLayout

Basically, you just need to integrate the PureLayout Objective-C source files into your project, and then import the `PureLayout.h` umbrella header from your Swift project's bridging header. If you aren't sure how to use a bridging header, Apple's documentation explains [how to set that up here](https://developer.apple.com/library/ios/documentation/Swift/Conceptual/BuildingCocoaApps/MixandMatch.html).

Let me know if you have any other questions. I'll try and get a real Swift sample project up and running soon.

**Comment by davehirsch** [comment]
Thanks, Tyler!  The TableCell example is just what I needed!
-Dave﻿

============================
Dave Hirsch
Associate Professor
Department of Geology
Western Washington University
alternate email: dhirsch@mac.com
http://www.davehirsch.com
cell: (360) 389-3583
work: (360) 650-2166
fb: http://www.facebook.com/dave.hirsch
============================

**Comment by smileyborg** [comment]
Great, glad it can help. If you don't mind I will leave this issue open and use it as a reminder to put together a real Swift sample project as part of PureLayout.

**Comment by sixfngers** [comment]
The swift sample you have on the repo works great, thanks.
However I cannot get the cocoapods install to work with a new xcode project.
The cocoapods install works but attempting to write some code fails to autocomplete and give errors.

Ex: let redView = UIView.newAutoLayoutView()
results in error UIView does not have a member named ...

I tried adding the bridging header but I cannot find the correct path to use in the import.

I can get the project to work if I drag and drop the files into the xcode project and setup the bridging header in the same manner as your sample project but I would really like to manage through cocoapods.

Any suggestions?

**Comment by smileyborg** [comment]
@sixfngers Glad you were able to get it working! I definitely plan to update the README to add some specific instructions, notes, and examples for Swift soon. One of the many things on the todo list :)

**Comment by mdio** [comment]
Unable to get the bridging header working I [found out](http://stackoverflow.com/a/28404825) that CocoaPods 0.36 introduced `use_frameworks!` especially for Swift and adding it to your Podfile enables you to simply do
```
import PureLayout
```
in your Swift code.

**Comment by smileyborg** [comment]
I've finally added Swift versions of all the existing iOS demos, and the iOS example app has been enhanced to easily switch between using the Objective-C and Swift versions. See b970c6f7bc483f28468d3d6b9010a3e90feefb86
