### ISSUE TITLE
Is there a way to remove all constraints on a UIView?

### ISSUE THREAD

**Issue by vordio** [smileyborg/PureLayout#57]
Seems it's not in the API?
When I wanna dynamically add/remove views it's not convenient.

**Comment by smileyborg** [comment]
Hi @vordio,

Thanks for asking. This is similar to the question in #56.

If you look at the [deprecated methods in ALView+PureLayout.h](https://github.com/smileyborg/PureLayout/blob/aa0ab1cb27f13967445c7c02859e46e63f8d3732/PureLayout/PureLayout/ALView%2BPureLayout.h#L233), you'll actually see some methods that do what you are asking.

So why are these methods deprecated? Well, take a look at the documentation for these methods:

    DEPRECATED as of PureLayout v2.0.0. Retain a reference to and remove specific constraints instead, or recreate the view(s) entirely to remove all constraints.
    Removes all explicit constraints that affect the view.
    WARNING: Apple's constraint solver is not optimized for large-scale constraint removal; you may encounter major performance issues after using this method.

As these comments suggest, the Auto Layout engine is not designed to handle deactivating and reactivating many constraints for views that have already been solved (laid out) once. The reason is because the Auto Layout engine tries to find the new solution for existing views based on their previous solution (from the old constraints). This strategy works great and is efficient if you only change one constraint on a view, but it is **much** slower and more computationally intensive if you are effectively starting from scratch with all-new constraints.

So, if you want to remove all constraints for a view, the easiest way is to remove that view from the view hierarchy (which automatically removes all of its constraints), and then re-add it into the view hierarchy again with new constraints. That's assuming you have a single view with no subviews of its own. If your view has some subviews and internal constraints that you also need to change, then you should discard the view (and its subviews) completely and create a new one from scratch -- the memory allocation and initialization for this will be much less expensive than reusing the views with completely different constraints.

Let me know if you have any additional questions!

**Comment by MarBaka** [comment]
Hi!
You can use this: 

`func removeAllConstraintsFromView(view: UIView) {
        for c in view.constraints {
              view.removeConstraint(c)
        }
     }`

(my first answer btw)
