### ISSUE TITLE
TableView inside ScrollView doesn't layout properly without init frame

### ISSUE THREAD

**Issue by kylebshr** [smileyborg/PureLayout#61]
This isn't so much an actual issue vs. me wondering why this is the case. I'm very new to this, and I hope it's not inappropriate to ask questions like this as an issue! If there's a better place to do this, please let me know. Allow me to describe:

I have a paged scroll view that is very wide and used to contain three different tableviews that can be swiped between, like so:

    -------------------------------
    |         |         |         |
    |   v1    |   v2    |   v3    |
    |         |         |         |
    -------------------------------

The scrollview itself is pinned to the view controllers edges. v1 is pinned to scrollview.leading, .top and v2 appropriately. It's height is view.frame.height, and width view.frame.width **set with autoSetHeight.** v2 has the same dimensions, and is pinned to scrollview.top, v1 on the left, and v3 on the right. v3 is set up like v1, but opposite of course. 

Now, with all these constraints, it should be layed out fine, and work as expected. I don't get any ambiguous or broken constraints messages. However, the tableviews simply don't appear. **If** I init them with a frame (even though that frame is later changed by the layout), then it works fine. 

Why is this? Thank you for your help!

Kyle

**Comment by smileyborg** [comment]
Scroll views (and table views, which is a subclass of scroll view) have some special behavior when it comes to interacting with auto layout.

Apple has a pretty good article about this here: [Technical Note TN2154: UIScrollView And Autolayout](https://developer.apple.com/library/ios/technotes/tn2154/_index.html)

If you read & understand that note, it may answer your question.

Generally speaking, I would say in this case you are much better off not using auto layout to position in the table views inside the scroll view. I would set their `frame` and the `scrollView.contentSize` manually so that it's a non-issue. There is no need to use auto layout if it's more difficult than not using it!

**Comment by smileyborg** [comment]
Closing this for now, let me know if you have other questions.
