### ISSUE TITLE
Dynamic height dimension

### ISSUE THREAD

**Issue by ton03** [smileyborg/PureLayout#72]
Hi, I'm pretty new to this

To put it simply, I have a facebook news feed looking app and I used purelayout on the box views. Their height are set to this:

```swift
view.autoSetDimension(ALDimension.Height, toSize: view.frame.height)
```

Images are loaded asynchronously, so the boxes need to resize dynamically via `layoutSubviews`

I attempted to resize the box using the code above but it shows a warning that says: `Probably at least one of the constraints in the following list is one you don't want. ...` so I know something's wrong. Also, my app looks pretty much ruined after the images loaded.

My box's init (box is a UIView subclass) already has the ff. code but I still have no idea how it would help my issue:

```swift
self.setTranslatesAutoresizingMaskIntoConstraints(false)
```

What am I doing wrong, and how can I resize my box's constraints properly?

**Comment by smileyborg** [comment]
Hi @ton03,

First of all, this is a general Auto Layout question -- I'll try to give you some details but please follow up by asking on Stack Overflow if you have further questions (these GitHub issues are for PureLayout-specific questions or problems).

I'm assuming you're using a UIImageView to display your images. If that's the case, when you set an image, the image view will automatically take on a new [intrinsic content size](http://stackoverflow.com/questions/22599069/what-is-the-content-compression-resistance-and-content-hugging-of-a-uiview) based on the image's size.

So, you don't want to actually add any height constraint to the image view like the one you shared above (using PureLayout or any other way). This is because if you do this, your height constraint is a fixed size (in this case, you're fixing the height to the view's current `frame.height`, and we know that will change once your image is set sometime later on) which means your view will be stuck at this height, and the intrinsic content size height will effectively be overridden since your constraint is higher priority.

Good luck!
