### ISSUE TITLE
Convenience methods for common use cases

### ISSUE THREAD

**Issue by pfleiner** [smileyborg/PureLayout#76]
I've been using PureLayout/UIView+AutoLayout for a long time now, and it's fantastic. Two of the most common use cases I've found to be simply pinning all edges to the superview edges and pinning exclusively to opposite edges. The first case is somewhat handled with iOS 8's ```layoutMargins```, but still requires some additional configuration and is unavailable on iOS 7.

I've written a few additional methods, mostly pertaining to the pinning of edges along an axis. I'd love to see them incorporated in the project.

https://gist.github.com/pfleiner/ff11d7fa5c0d796366a1

**Comment by smileyborg** [comment]
Hi Paul,

Thanks for these suggestions! It's great to see suggestions for new API based on real world use cases (a while back in #12 there was a similar example).

Anyways, for your suggested additions, I completely understand the use cases for all of them.

The general guideline I have followed is that each new method on the public API should do one of the following:

* Solve a completely new use case
* Simplify an existing use case that requires 3 or more lines of code
* Provide a version of an existing method but with more/less parameters

These aren't hard and fast rules, but the general idea is to be fairly judicious about expanding the public API to avoid making it unwieldy and overly complicated.

In this case, I am in agreement that the method `autoPinEdgesToSuperviewEdges` would be useful. This falls under the last bullet point above. Typically this is done with the current API by just calling `[view autoPinEdgesToSuperviewEdgesWithInsets:UIEdgeInsetsZero]`. But I think it does make sense to expose this variant that defaults to zero insets.

As far as the other 3 methods you proposed, each of those is responsible for reducing 2 lines of code into 1. While I agree that they are useful, I don't think they provide enough value on their own to justify increasing the public API surface. (The reason that [this API exists](https://github.com/smileyborg/PureLayout/blob/e2e75ab9bcdf5b75ddeb8ac85f9f5093b980f46c/PureLayout/PureLayout/ALView%2BPureLayout.h#L111) is because it just barely crosses the threshold of the second bullet.)

What do you think?

**Comment by pfleiner** [comment]
I would definitely appreciate not typing UI/ALEdgeInsetsZero quite so much!

Ah, ok, I wasn't aware of the 3 line guideline. In that case, I've found that almost every time I'm pinning a subview to two edges on an axis, I'm also aligning the axes as well. Not sure how broad of a use case that is, but I've found myself using it time and time again.

**Comment by smileyborg** [comment]
The 3-line guideline is just something I have personally adhered to...it's not a published rule or anything.

And the methods you shared only pin 2 edges, they aren't also aligning -- did you mean to suggest something like a one-line call that does all of this?

```
[view1 autoPinEdgeToSuperviewEdge:ALEdgeLeading];
[view1 autoPinEdgeToSuperviewEdge:ALEdgeTrailing];
[view1 autoAlignAxisToSuperviewAxis:ALAxisVertical];
```

If so, that last constraint is actually not necessary. The horizontal layout is fully specified by just the first 2 constraints.

**Comment by pfleiner** [comment]
I meant aligning the subview to the same axis to which it's edges are being pinned:
```objc
[view1 autoPinEdgeToSuperviewEdge:ALEdgeLeading];
[view1 autoPinEdgeToSuperviewEdge:ALEdgeTrailing];
[view1 autoAlignAxisToSuperviewAxis:ALAxisHorizontal];
```
could be reduced to
```objc
[view1 autoAlignAndPinEdgesToSuperviewEdgesOnAxis:ALAxisHorizontal];
```
or
```objc
[view1 autoPinEdgesToSuperviewEdgesOnAxis:ALAxisHorizontal alignment:YES];
```
Just typing these methods out, however, they seem pretty specific, and including any additional parameters would be a pain. Plus there's the matter of returning the array of constraints in an intuitive order. I'm not necessarily lobbying for this exactly, I guess I'm mainly interested hearing how you'd approach it.

**Comment by smileyborg** [comment]
Oh, I see what you mean. Yeah, I don't think that this is common or general enough for a new API. I do think that this is a perfectly reasonable extension to use in your own code though, if you do find it coming up!

**Comment by smileyborg** [comment]
Thanks again for the suggestions!!
