### ISSUE TITLE
Crash for newAutoLayoutView

### ISSUE THREAD

**Issue by KingWu** [smileyborg/PureLayout#86]
i just add some codes from sample in my project

    @objc(LoginViewController)
    class LoginViewController : UIViewController, FBSDKLoginButtonDelegate {

    let blueView: UIView = {
        let view = UIView.newAutoLayoutView()
        view.backgroundColor = .blueColor()
        return view
        }()

Then add these crashs

    [UIView newAutoLayoutView]: unrecognized selector sent to class 0x10bfb71c8
    *** Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: '+[UIView newAutoLayoutView]: unrecognized selector sent to class 0x10bfb71c8'

what things i missed?

**Comment by smileyborg** [comment]
Hi Wu,

It's hard to say for sure exactly what is happening. Here are a few questions to help narrow it down:

1. How are you integrating PureLayout into your project? (Did you use CocoaPods, Carthage, or just drag the source files into your project?)
2. How are you importing PureLayout into your Swift code?
3. This crash looks to me like a possible linker issue. Can you try adding the `-all_load` and `-ObjC` linker flags to the target in your Xcode project where you are trying to use PureLayout? These linker flags are important because PureLayout is implemented using categories. Here is some [further discussion](http://stackoverflow.com/a/21844874/796419) about these flags.

  Using the PureLayout example app, here is a screenshot of where you should add those linker flags:
  <img width="1207" alt="screen shot 2015-08-29 at 8 53 33 am" src="https://cloud.githubusercontent.com/assets/1372557/9562793/9aec7b2e-4e2b-11e5-938a-41de7873c51e.png">

**Comment by KingWu** [comment]
@smileyborg Thanks. I found that i miss steps on Carthage setup. Just add linkage. Then work.

**Comment by smileyborg** [comment]
Great, thanks for the update!
